export const AUDIT_ENTITY_TYPE = {
  USER: 'USER',
  STUDENT: 'STUDENT',
  RECRUITER: 'RECRUITER',
  COMPANY: 'COMPANY',
  PLACEMENT_DRIVE: 'PLACEMENT_DRIVE',
  APPLICATION: 'APPLICATION',
  ELIGIBILITY_CRITERIA: 'ELIGIBILITY_CRITERIA',
  NOTIFICATION: 'NOTIFICATION',
}