export const NOTIFICATION_TYPE = {
  DRIVE: 'DRIVE',
  APPLICATION: 'APPLICATION',
  SHORTLISTED: 'SHORTLISTED',
  RESULT: 'RESULT',
  RECRUITMENT_ACTIVITY: 'RECRUITMENT_ACTIVITY',
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  SYSTEM: 'SYSTEM',
}