export const RECRUITMENT_ACTIVITY = {
  APTITUDE_TEST: 'APTITUDE_TEST',
  CODING_TEST: 'CODING_TEST',
  TECHNICAL_TEST: 'TECHNICAL_TEST',
  GROUP_DISCUSSION: 'GROUP_DISCUSSION',
  TECHNICAL_INTERVIEW: 'TECHNICAL_INTERVIEW',
  HR_INTERVIEW: 'HR_INTERVIEW',
  MANAGERIAL_INTERVIEW: 'MANAGERIAL_INTERVIEW',
  OTHER: 'OTHER',
}

export const RECRUITMENT_ACTIVITY_LABELS = {
  [RECRUITMENT_ACTIVITY.APTITUDE_TEST]: 'Aptitude Test',
  [RECRUITMENT_ACTIVITY.CODING_TEST]: 'Coding Test',
  [RECRUITMENT_ACTIVITY.TECHNICAL_TEST]: 'Technical Test',
  [RECRUITMENT_ACTIVITY.GROUP_DISCUSSION]: 'Group Discussion',
  [RECRUITMENT_ACTIVITY.TECHNICAL_INTERVIEW]: 'Technical Interview',
  [RECRUITMENT_ACTIVITY.HR_INTERVIEW]: 'HR Interview',
  [RECRUITMENT_ACTIVITY.MANAGERIAL_INTERVIEW]: 'Managerial Interview',
  [RECRUITMENT_ACTIVITY.OTHER]: 'Other',
}