spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/pms_db?createDatabaseIfNotExist=true
    username: project_user
    password: project
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
